Contato contato1 = new Contato();
Console.Write("Nome: ");
contato1.NomeContato = Console.ReadLine()!;
Console.Write("Telefone: ");
contato1.TelefoneContato = Convert.ToInt32(Console.ReadLine());
Console.Write("Email: ");
contato1.EmailContato = Console.ReadLine()!;
contato1.Endereco = new Endereco();
Console.Write("Logradouro: ");
contato1.Endereco.LogradouroContato = Console.ReadLine()!;
Console.Write("Numero: ");
contato1.Endereco.NumeroContato = Convert.ToInt32(Console.ReadLine());
Console.Write("Complemento: ");
contato1.Endereco.ComplementoContato = Console.ReadLine()!;
Console.Write("Bairro: ");
contato1.Endereco.BairroContato = Console.ReadLine()!;
Console.Write("Cidade: ");
contato1.Endereco.CidadeContato = Console.ReadLine()!;
Console.Write("UF: ");
contato1.Endereco.UfContato = Console.ReadLine()!;